# /.github/workflows/deploy.yml
name: Deploy
on:
  repository_dispatch:
    types: [update_post]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run build
    - run: npm run deploy
